= Simple Meetup

image:https://travis-ci.org/michael-simons/simple-meetup.svg?branch=master["Build Status", link="https://travis-ci.org/michael-simons/simple-meetup"]

A sample project to explore

* Gradle
* Domain-driven Design
* Test-driven Development
* Living documentation

based on a Spring Boot application.

== Domain

The application should provide a REST-API for managing events and registering for those events. Events must be unique by name on a given day. They can be open and close and have a number of seats available. The number of free seats must be computed by through the current number of registrations. A person can register exactly one time with a given email address.

== Build

You'll need Java 8 and Docker installed to build the project. Just run

```
./gradlew
```

or

```
./gradlew.bat
```

depending wether you're on a Unix-like- or Windows-Machine.

== Thanks

In no specific order to

* my wife https://twitter.com/tinasimons[Christina] for fixing most of my spelling errors in the articles
* https://rdmueller.github.io[Ralf D. Müller], for his work on the https://github.com/docToolchain/docToolchain[docToolChain] and his feedback on the testing article
* my awesome colleagues at https://innoq.com[innoQ] for their feedback on the project and the article
